export const employees = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    startDate: '2021-04-01',
    dateOfBirth: '1990-01-01',
    street: '123 Main St',
    city: 'New York',
    state: 'New York',
    zipCode: '10001',
    department: 'Sales',
  },
  {
    id: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    startDate: '2022-01-23',
    dateOfBirth: '1985-06-15',
    street: '456 Elm St',
    city: 'Los Angeles',
    state: 'California',
    zipCode: '90012',
    department: 'Marketing',
  },
  {
    id: 3,
    firstName: 'Alice',
    lastName: 'Johnson',
    startDate: '2022-05-01',
    dateOfBirth: '1988-09-30',
    street: '789 Oak Ave',
    city: 'Chicago',
    state: 'Illinois',
    zipCode: '60611',
    department: 'Engineering',
  },
  {
    id: 4,
    firstName: 'Michael',
    lastName: 'Brown',
    startDate: '2022-01-01',
    dateOfBirth: '1975-03-20',
    street: '101 Pine Rd',
    city: 'Houston',
    state: 'Texas',
    zipCode: '77002',
    department: 'Finance',
  },
  {
    id: 5,
    firstName: 'Sarah',
    lastName: 'Wilson',
    startDate: '2021-01-01',
    dateOfBirth: '1992-05-10',
    street: '222 Maple St',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    zipCode: '19103',
    department: 'Human Resources',
  },
  {
    id: 6,
    firstName: 'David',
    lastName: 'Miller',
    startDate: '2020-01-01',
    dateOfBirth: '1978-08-25',
    street: '333 Oak St',
    city: 'San Francisco',
    state: 'California',
    zipCode: '94101',
    department: 'IT',
  },
  {
    id: 7,
    firstName: 'Emily',
    lastName: 'Davis',
    startDate: '2022-01-01',
    dateOfBirth: '1987-11-15',
    street: '555 Pine Rd',
    city: 'Boston',
    state: 'Massachusetts',
    zipCode: '02115',
    department: 'Customer Service',
  },
  {
    id: 8,
    firstName: 'Daniel',
    lastName: 'Garcia',
    startDate: '2021-01-01',
    dateOfBirth: '1995-02-20',
    street: '777 Elm St',
    city: 'Seattle',
    state: 'Washington',
    zipCode: '98101',
    department: 'Legal',
  },
  {
    id: 9,
    firstName: 'Olivia',
    lastName: 'Rodriguez',
    startDate: '2022-01-01',
    dateOfBirth: '1993-07-05',
    street: '888 Oak Ave',
    city: 'Miami',
    state: 'Florida',
    zipCode: '33101',
    department: 'Operations',
  },
  {
    id: 10,
    firstName: 'Matthew',
    lastName: 'Martinez',
    startDate: '2021-01-01',
    dateOfBirth: '1989-04-12',
    street: '999 Pine St',
    city: 'Dallas',
    state: 'Texas',
    zipCode: '75201',
    department: 'Sales',
  },
  {
    id: 11,
    firstName: 'Sophia',
    lastName: 'Hernandez',
    startDate: '2022-01-01',
    dateOfBirth: '1991-09-28',
    street: '111 Maple Ave',
    city: 'San Diego',
    state: 'California',
    zipCode: '92101',
    department: 'Marketing',
  },
  {
    id: 12,
    firstName: 'James',
    lastName: 'Lopez',
    startDate: '2022-01-01',
    dateOfBirth: '1986-12-15',
    street: '222 Pine Rd',
    city: 'Austin',
    state: 'Texas',
    zipCode: '78701',
    department: 'Engineering',
  },
  {
    id: 13,
    firstName: 'Emma',
    lastName: 'Gonzalez',
    startDate: '2021-01-01',
    dateOfBirth: '1994-07-02',
    street: '333 Oak St',
    city: 'Phoenix',
    state: 'Arizona',
    zipCode: '85001',
    department: 'Finance',
  },
  {
    id: 14,
    firstName: 'Benjamin',
    lastName: 'Perez',
    startDate: '2022-01-01',
    dateOfBirth: '1985-03-10',
    street: '444 Pine Rd',
    city: 'San Antonio',
    state: 'Texas',
    zipCode: '78205',
    department: 'Human Resources',
  },
  {
    id: 15,
    firstName: 'Charlotte',
    lastName: 'Taylor',
    startDate: '2021-01-01',
    dateOfBirth: '1990-08-25',
    street: '555 Oak St',
    city: 'Denver',
    state: 'Colorado',
    zipCode: '80202',
    department: 'IT',
  },
]
