export const employees = [
  {
    id: 1,
    firstname: 'John',
    lastname: 'Doe',
    startDate: '2021-04-01',
    dateOfBirth: '1990-01-01',
    street: '123 Main St',
    city: 'New York',
    state: 'New York',
    zipcode: '10001',
    department: 'Sales',
  },
  {
    id: 2,
    firstname: 'Jane',
    lastname: 'Smith',
    startDate: '2022-01-23',
    dateOfBirth: '1985-06-15',
    street: '456 Elm St',
    city: 'Los Angeles',
    state: 'California',
    zipcode: '90012',
    department: 'Marketing',
  },
  {
    id: 3,
    firstname: 'Alice',
    lastname: 'Johnson',
    startDate: '2022-05-01',
    dateOfBirth: '1988-09-30',
    street: '789 Oak Ave',
    city: 'Chicago',
    state: 'Illinois',
    zipcode: '60611',
    department: 'Engineering',
  },
  {
    id: 4,
    firstname: 'Michael',
    lastname: 'Brown',
    startDate: '2022-01-01',
    dateOfBirth: '1975-03-20',
    street: '101 Pine Rd',
    city: 'Houston',
    state: 'Texas',
    zipcode: '77002',
    department: 'Finance',
  },
  {
    id: 5,
    firstname: 'Sarah',
    lastname: 'Wilson',
    startDate: '2021-01-01',
    dateOfBirth: '1992-05-10',
    street: '222 Maple St',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    zipcode: '19103',
    department: 'Human Resources',
  },
  {
    id: 6,
    firstname: 'David',
    lastname: 'Miller',
    startDate: '2020-01-01',
    dateOfBirth: '1978-08-25',
    street: '333 Oak St',
    city: 'San Francisco',
    state: 'California',
    zipcode: '94101',
    department: 'IT',
  },
  {
    id: 7,
    firstname: 'Emily',
    lastname: 'Davis',
    startDate: '2022-01-01',
    dateOfBirth: '1987-11-15',
    street: '555 Pine Rd',
    city: 'Boston',
    state: 'Massachusetts',
    zipcode: '02115',
    department: 'Customer Service',
  },
]
